# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ 
  haskellPackages ? (import <nixpkgs> {}).haskellPackages}:
let inherit
   (haskellPackages)
  cabal acidState aeson async datetime hslogger hspec
  httpStreams ioStreams mtl QuickCheck safecopy text time
  transformers unorderedContainers url websockets
  haste-compiler 
  cabalInstall;



in cabal.mkDerivation (self: {
  pname = "erp";
  version = "0.0.0.2";
  src = ./.;
  isLibrary = true;
  isExecutable = true;
  buildDepends = [
    acidState aeson async datetime hslogger hspec httpStreams ioStreams
    mtl safecopy text time transformers unorderedContainers url
    websockets
  ];
  testDepends = [
    acidState aeson async datetime hslogger hspec httpStreams mtl
    QuickCheck safecopy text time unorderedContainers url websockets
  ];
  buildTools = [cabalInstall];
  meta = {
    homepage = "tbd";
    description = "Create a data model for erp";
    license = "GPL";
    platforms = self.ghc.meta.platforms;
  };
})
